### ISSUE TITLE
搭建的allinone看斗鱼之类的外面封面延迟显示很高，观看无影响，有什么解决办法没，有点强迫症：）

### ISSUE THREAD

**Issue by bingbaicai** [youshandefeiyang/LiveRedirect#40]
如题所述
![photo_2023-07-04_16-37-45](https://github.com/youshandefeiyang/LiveRedirect/assets/66243694/74e3ef90-617b-48ff-a739-ae47fea54dbe)

**Comment by youshandefeiyang** [comment]
解决办法很简单，你用国内vps秒开
