### ISSUE TITLE
douyin vr 的m3u8获取错误

### ISSUE THREAD

**Issue by EvilMir** [youshandefeiyang/LiveRedirect#41]
http://127.0.0.1:35455/douyin?url=https://v.douyin.com/iJJtMvwb/

返回的是
http://159.75.85.63:5680/d/ad/roomad/playlist.m3u8
内容是直播间未开

实际上douyin里直播间开着的

**Comment by youshandefeiyang** [comment]
接口间歇性失灵，暂时找不到好的接口
