### ISSUE TITLE
bilibili画质参数设置无效了

### ISSUE THREAD

**Issue by withtea** [youshandefeiyang/LiveRedirect#48]
bilibili画质参数设置无效了

**Comment by zheyiyuezhuo** [comment]
感觉是不登陆账号的话画质就默认最糊
![图片](https://github.com/youshandefeiyang/LiveRedirect/assets/46232425/c35251a7-47c3-4557-9948-b11e1ecb7e3c)

**Comment by youshandefeiyang** [comment]
未登录部分直播间就是低画质，平台限制

**Comment by zheyiyuezhuo** [comment]
> 未登录部分直播间就是低画质，平台限制

能否加一个添加cookies的选项或者可以手动登陆获得高画质
