### ISSUE TITLE
可以添加一个能够检测是否开播的参数吗

### ISSUE THREAD

**Issue by user00036** [youshandefeiyang/LiveRedirect#54]
因为直接ip/douyu/xxxx这种，无法判断是否开播。

**Comment by youshandefeiyang** [comment]
没开播播放的是我的广告。。。

**Comment by user00036** [comment]
> 没开播播放的是我的广告。。。

嗯，但是我想用代码请求然后批量检测是否开播。或者请求得到的是url，我自己处理也可以。不然我没法批量检测是否开播就很尴尬
