### ISSUE TITLE
time.LoadLocation 报错 

### ISSUE THREAD

**Issue by creeed** [youshandefeiyang/LiveRedirect#61]
location, _ := time.LoadLocation("Asia/Shanghai")  报错 
panic recovered:
time: missing Location in call to Time.In
C:/Program Files/Go/src/time/time.go:1122 (0x75d44d)

替换成如下
	location, err := time.LoadLocation("Asia/Shanghai") //设置时区
	if err != nil {
		location = time.FixedZone("CST", 8*3600) //替换上海时区
	}
	now := time.Now().In(location)

报错没了， 但是虎牙仍然无法播放

**Comment by youshandefeiyang** [comment]
虎牙确实可以播放fix
