### ISSUE TITLE
请问虎牙的直播源在哪里抓取到的

### ISSUE THREAD

**Issue by zsl-157** [youshandefeiyang/LiveRedirect#63]
请问作者的虎牙直播源在网页抓到的还是app呢，为什么我抓到的ctype都是tars_mobile，这样的都只能播放两分钟。作者的是tars_mp是正常的。想重新抓一遍学习一下

**Comment by youshandefeiyang** [comment]
https://mp.huya.com/cache.php?m=Live&do=profileRoom&roomid=
