### ISSUE TITLE
2024.5.30 虎牙报错 panic recovered

### ISSUE THREAD

**Issue by zqs1qiwan** [youshandefeiyang/LiveRedirect#64]
日志输出如下：
2024/05/30 12:07:15 [Recovery] 2024/05/30 - 12:07:15 panic recovered:
runtime error: index out of range [1] with length 0
/usr/local/go/src/runtime/panic.go:113 (0x43561e)
/app/liveurls/huya.go:160 (0x9539db)
/app/main.go:161 (0xaff7a4)
/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173 (0xaf5201)
/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/recovery.go:101 (0xaf51ec)
/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173 (0xaf4306)
/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/logger.go:240 (0xaf42e9)
/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173 (0xaf33d0)
/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/gin.go:616 (0xaf3038)
/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/gin.go:572 (0xaf2b7c)
/usr/local/go/src/net/http/server.go:2947 (0x6c06cb)
/usr/local/go/src/net/http/server.go:1991 (0x6bb8e6)
/usr/local/go/src/runtime/asm_amd64.s:1594 (0x4682c0)
[GIN] 2024/05/30 - 12:07:15 | 500 |  243.343698ms |   192.168.2.144 | GET      "/huya/406324"

斗鱼正常播放，其他平台未测试。

**Comment by youshandefeiyang** [comment]
已修复
