### ISSUE TITLE
更改bilibili接口

### ISSUE THREAD

**Issue by written143** [youshandefeiyang/LiveRedirect#67]
https://api.live.bilibili.com/room/v1/Room/playUrl?cid=直播间房间号&platform=hls&otype=json&quality=4

platform这里填hls或者flv可以解决一些直播间打不开的问题
h5获取的是m3u8已经不能播放了web也只有一部分直播间能看

**Comment by youshandefeiyang** [comment]
我这边测试改为h5反而正常？

**Comment by youshandefeiyang** [comment]
不小心关闭了，回复我能看到的

**Comment by youshandefeiyang** [comment]
完了我抽空看看

**Comment by youshandefeiyang** [comment]
那意思是直接默认flv更合适？也不知道这个接口能用多久，不加cookie能获取到高清直播源地址的接口很难得了

**Comment by youshandefeiyang** [comment]
收到

written143 ***@***.***> 于 2024年7月31日周三 05:39写道：
