### ISSUE TITLE
B站api可能还是有点问题

### ISSUE THREAD

**Issue by written143** [youshandefeiyang/LiveRedirect#69]
链接放在potplayer上无法播放
放到浏览器解析后的地址复制到potplayer可以播放
![image](https://github.com/user-attachments/assets/0a8b523a-da30-427f-844f-4a04bb553a02)
![image](https://github.com/user-attachments/assets/3d50ba69-c2b2-4523-a142-52e35fd8ab37)

**Comment by youshandefeiyang** [comment]
potplayer的问题，把platform改成hls即可
